### ISSUE TITLE
样式背景图片缺失

### ISSUE THREAD

**Issue by Hill-98** [seatonjiang/kratos#113]
```css
.kratos-theme-post .cate-bk {
	display: inline-block;
	width: 30px;
	height: 29px;
	background-image: url(../images/download.png);
	background-size: 30px 29px;
	text-indent: -999em
}
```
`../images/download.png` 这个文件不存在的吧，而且这个相对链接变成绝对链接以后，就是这个`http://example.com/wp-content/themes/images/download.png`样子了，这明显不正确啊。
