### ISSUE TITLE
代码显示有问题，会有边框

### ISSUE THREAD

**Issue by y001j** [seatonjiang/kratos#126]
**问题描述**

代码块会有方框，或者每行代码带有上下的横线

**产生环境**

- 设备：PC
- 浏览器及版本：Chrome
- 演示地址：已经修改style文件

**修复建议**
修改了style.css文件的code部分, 注释掉border这一行
```css
code {
	padding: 2px 4px;
	font-size: 90%;
	color: #333;
	background-color: #f8f8f8;
	border-radius: 0;
        /* border: 1px solid #E1E1E1; */
	margin: 0 5px
}
```
