### ISSUE TITLE
文章图片居中有问题

### ISSUE THREAD

**Issue by Hill-98** [seatonjiang/kratos#170]
```css
.k-main .details .article .content .aligncenter {
	margin-right: auto;
	margin-left: auto;
}
```
这样的居中样式只对块元素起作用，但是 c19236f863b8b5de70930fdd98e84d649c739cf2 提交把 `display: block;` 删掉了，不知道出于合意？
