### ISSUE TITLE
颜色导航顶部不对称

### ISSUE THREAD

**Issue by jalena** [seatonjiang/kratos#295]
**问题描述**
在使用**颜色导航**时应该取消

```css
@media screen and (min-width: 782px) {
                .k-nav{
                    padding-top: 32px;
                }
            }
```
否则顶部会padding-top: 32px，看着不对称。

还有这个主题只支持2级菜单哇，我看到代码里面你写死了，只输出2个层级!？

**环境信息**
PHP 版本：7.4.10
Kratos 版本：3.2.0
WordPress 版本：5.5.1
User Agent 信息：Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

**复现步奏**
None
