### ISSUE TITLE
建议增加右侧栏可以随屏滚动功能

### ISSUE THREAD

**Issue by niux45** [seatonjiang/kratos#324]
现在很多主题都可以让右侧栏随着屏幕滚动，这样就可以让右侧一些重要的东西始终能让读者看到，希望能增加这个实用的功能

**Comment by seatonjiang** [comment]
这个之前版本有，后来因为兼容问题给下掉了，过年研究一下

**Comment by cyfrit** [comment]
https://imold.wang/wordpress/153.html
我用没有问题

**Comment by Jomixedyu** [comment]
附议

**Comment by seatonjiang** [comment]
新版本已经加上这个功能了，等推送更新即可。

**Comment by n0099** [comment]
纯css能够实现sticky就请尽量不要引入外部js库
```css
div.sidebar {
    display: block !important; #这行不必要因为我是在子主题中声明才需要这样覆盖的
    position: sticky;
    height: 100%;
    top: 36px;
}
```
