### ISSUE TITLE
建议添加一个文章内图片可以点击查看放大的功能

### ISSUE THREAD

**Issue by CuteLeaf** [seatonjiang/kratos#393]
**问题描述**
建议添加一个文章内图片可以点击查看放大的功能

**环境信息**

**复现步奏**

**Comment by n0099** [comment]
建议
```css
img {
width: 50%;
object-fit: scale-down
}
```
缓解
